# Runs to avoid database at Supabase to enter sleep-mode (https://supabase.com/docs/going-into-prod#availability)
name: Keep DB awake

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  render:
    name: Keep DB awake
    runs-on: ubuntu-latest

    steps:
      - name: Send event event
        id: request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://stats.olafros.com/api/olros/stats/event/'
          method: 'POST'
          timeout: 20000
          customHeaders: '{"Origin": "https://stats.olafros.com"}'
          data: '{"name": "keep-awake"}'
      - name: Respons
        run: |
          echo ${{ steps.request.outputs.response }}
