name: Migrate Database

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Set DATABASE_URL .env-variables
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env

      - name: Migrate
        run: npx prisma migrate deploy