/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  serverDependenciesToBundle: [
    /^@nivo\/.*/,
    /^@react-spring\/.*/,
    /^d3-.*/,
    'delaunator',
    'internmap',
    'react-lifecycles-compat',
    '@olros/stats',
    /^remix-utils.*/,
    'is-ip',
    'ip-regex',
    'super-regex',
    'clone-regexp',
    'function-timeout',
    'time-span',
    'convert-hrtime',
    'is-regexp',
    /^@turf\/.*/,
    '@tweenjs/tween.js',
    'accessor-fn',
    'data-joint',
    'delaunator',
    'globe.gl',
    'h3-js',
    'index-array-by',
    'internmap',
    'jerrypick',
    'kapsule',
    /^lodash-es.*/,
    'polished',
    'react-globe.gl',
    'react-kapsule',
    'robust-predicates',
    /^three.*/,
    'tinycolor2',
    'date-fns',
  ],
  serverMinify: true,
  serverModuleFormat: 'cjs',
};
