/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  serverDependenciesToBundle: [
    '@prisma/client',
    '@prisma/client/runtime/library',
    'd3-time-format',
    'd3-color',
    /^@nivo.*/,
    /^date-fns.*/,
    /^lodash.*/,
    /^@react-spring.*/,
    /^remix-utils.*/,
    'is-ip',
    'ip-regex',
    'super-regex',
    'clone-regexp',
    'function-timeout',
    'time-span',
    'convert-hrtime',
    'is-regexp',
  ],
  serverMinify: true,
  serverModuleFormat: 'cjs',
};
